authors:
  davidecristanelli:
    name: Davide Cristanelli
    description: AI & SW Engineer
    avatar: https://0.gravatar.com/avatar/90df5a725a9210be4094176797706b47e972b9ae334dc51252033ba2746df7fc?size=512&d=initials
    url: https://www.linkedin.com/in/dcristanelli/